### ISSUE TITLE
Shader warning in 'kode80/PixelRender/PixelArtShader' in Unity 5.3.5f1 

### ISSUE THREAD

**Issue by leebrarian** [kode80/PixelRenderUnity3D#1]
After initial import into a Unity 5.3.5f1 project, the following warning appears: 

```
Shader warning in 'kode80/PixelRender/PixelArtShader': Output value 'vert' is not completely initialized at line 82 (on d3d11)

Compiling Vertex program with DIRECTIONAL SHADOWS_OFF LIGHTMAP_OFF DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING
```

Adding **UNITY_INITIALIZE_OUTPUT(v2f, o);** after line 84, appears to resolve the issue. Lines 84 - 86 end up looking like this: 

```
                v2f o;
                UNITY_INITIALIZE_OUTPUT(v2f, o);
                o.pos = mul(UNITY_MATRIX_MVP, v.pos);
```

(Interestingly, it seems that once the warning has cleared, the newly introduced line can be removed.)

**Comment by kode80** [comment]
I believe this is because you're not using a normal map in your material, so it's not calculating the tangent space, yet they are still defined in the output struct. I'll fix this and push it to the main repo over the weekend.

In the meantime you can easily fix in your local copy by wrapping the tspace0, tspace1, tspace2 fields of the v2f struct in #if _NORMALMAP  #endif

**Comment by kode80** [comment]
I've fixed this warning in the the latest patch release (1.2.2). Thanks for bringing this to my attention!
